import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { AppProvider } from './provider';
import SideBar from '../components/SideBar';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['500', '600'],
    variable: '--pop',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.className} min-w-7xl flex justify-center bg-gray-300 pl-14 pr-14`}
            >
                <AppProvider>
                    <SideBar />
                    {children}
                </AppProvider>
            </body>
        </html>
    );
}
